### ISSUE TITLE
Do you think about `sectionbreak` package?

### ISSUE THREAD

**Issue by hidaruma** [hentaigirls/a5book#4]
sectionbreakパッケージというのがCTANにあった。大して複雑なパッケージではないし
よりプリミティブな命令でやっているものの、決め打ちでやってる`\Sepa`と置きかえるほどでもない。

次のコードで現在と実質同じ挙動になるかな？

```tex
\usepackage[mark={＊}, sep=1\zh]{sectionbreak}
\newcommand{\Sepa}{\sectionbreak}
```

**Comment by amane-katagiri** [comment]
情報ありがとうございます。行間が微妙に変わる部分がありましたので調整しつつ導入します。

**Comment by hidaruma** [comment]
文書の途中で

```tex
\sectionbreakmark{<hoge>}
```
されると<hoge>に置き変わっちゃったりするっぽいですね

**Comment by amane-katagiri** [comment]
66010ad で対応して v1.6 に反映しました。 `\Sepa` は互換性のためいったん残しましたが、例では `\sectionbreak` にしてあります。
